# This is a basic workflow to help you get started with Actions
on:
  push:
    branches: (**)

name: Lint Markdown files
jobs:
  markdown_lint:
    name: Check Markdown files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
